import { PERMISSION_GROUP, PERMISSION_RESOURCE } from '../permission.constant';

const ACTION_CONST = {
  CREATE: 'create',
  LIST: 'list',
  UPDATE: 'update',
  DETAIL: 'detail',
  DISABLE: 'disable',
  IMPORT: 'import',
  DELETE: 'delete',
  COORDINATE: 'coordinate',
};

export const DATA_PERMISSION = [
  {
    action: ACTION_CONST.LIST,
    resource: PERMISSION_RESOURCE.USER,
    name: 'Xem danh sách người dùng',
    group: PERMISSION_GROUP.ADMIN,
  },
  {
    action: ACTION_CONST.DETAIL,
    resource: PERMISSION_RESOURCE.USER,
    name: 'Xem chi tiết người dùng',
    group: PERMISSION_GROUP.ADMIN,
  },
  {
    action: ACTION_CONST.CREATE,
    resource: PERMISSION_RESOURCE.USER,
    name: 'Thêm mới người dùng',
    group: PERMISSION_GROUP.ADMIN,
  },
  {
    action: ACTION_CONST.UPDATE,
    resource: PERMISSION_RESOURCE.USER,
    name: 'Chỉnh sửa người dùng',
    group: PERMISSION_GROUP.ADMIN,
  },
  {
    action: ACTION_CONST.DISABLE,
    resource: PERMISSION_RESOURCE.USER,
    name: 'Vô hiệu hóa người dùng',
    group: PERMISSION_GROUP.ADMIN,
  },
  {
    action: ACTION_CONST.IMPORT,
    resource: PERMISSION_RESOURCE.USER,
    name: 'Import tài liệu',
    group: PERMISSION_GROUP.ADMIN,
  },
  {
    action: ACTION_CONST.LIST,
    resource: PERMISSION_RESOURCE.PERMISSION,
    name: 'Xem danh sách phân quyền',
    group: PERMISSION_GROUP.ADMIN,
  },
  {
    action: ACTION_CONST.DETAIL,
    resource: PERMISSION_RESOURCE.PERMISSION,
    name: 'Xem chi tiết nhóm quyền',
    group: PERMISSION_GROUP.ADMIN,
  },
  {
    action: ACTION_CONST.CREATE,
    resource: PERMISSION_RESOURCE.PERMISSION,
    name: 'Thêm mới nhóm quyền',
    group: PERMISSION_GROUP.ADMIN,
  },
  {
    action: ACTION_CONST.UPDATE,
    resource: PERMISSION_RESOURCE.PERMISSION,
    name: 'Chỉnh sửa nhóm quyền',
    group: PERMISSION_GROUP.ADMIN,
  },
  {
    action: ACTION_CONST.DELETE,
    resource: PERMISSION_RESOURCE.PERMISSION,
    name: 'Xóa nhóm quyền',
    group: PERMISSION_GROUP.ADMIN,
  },
  {
    action: ACTION_CONST.LIST,
    resource: PERMISSION_RESOURCE.CONFIGURATION,
    name: 'Xem danh sách danh mục',
    group: PERMISSION_GROUP.ADMIN,
  },
  {
    action: ACTION_CONST.DETAIL,
    resource: PERMISSION_RESOURCE.CONFIGURATION,
    name: 'Xem chi tiết danh mục',
    group: PERMISSION_GROUP.ADMIN,
  },
  {
    action: ACTION_CONST.CREATE,
    resource: PERMISSION_RESOURCE.CONFIGURATION,
    name: 'Thêm mới danh mục',
    group: PERMISSION_GROUP.ADMIN,
  },
  {
    action: ACTION_CONST.UPDATE,
    resource: PERMISSION_RESOURCE.CONFIGURATION,
    name: 'Chỉnh sửa danh mục',
    group: PERMISSION_GROUP.ADMIN,
  },
  {
    action: ACTION_CONST.DELETE,
    resource: PERMISSION_RESOURCE.CONFIGURATION,
    name: 'Xóa danh mục',
    group: PERMISSION_GROUP.ADMIN,
  },
  {
    action: ACTION_CONST.LIST,
    resource: PERMISSION_RESOURCE.ELECTRIC_VEHICLE,
    name: 'Xem danh sách xe điện',
    group: PERMISSION_GROUP.VEHICLE,
  },
  {
    action: ACTION_CONST.DETAIL,
    resource: PERMISSION_RESOURCE.ELECTRIC_VEHICLE,
    name: 'Xem chi tiết xe điện',
    group: PERMISSION_GROUP.VEHICLE,
  },
  {
    action: ACTION_CONST.CREATE,
    resource: PERMISSION_RESOURCE.ELECTRIC_VEHICLE,
    name: 'Thêm mới xe điện',
    group: PERMISSION_GROUP.VEHICLE,
  },
  {
    action: ACTION_CONST.UPDATE,
    resource: PERMISSION_RESOURCE.ELECTRIC_VEHICLE,
    name: 'Chỉnh sửa xe điện',
    group: PERMISSION_GROUP.VEHICLE,
  },
  {
    action: ACTION_CONST.DELETE,
    resource: PERMISSION_RESOURCE.ELECTRIC_VEHICLE,
    name: 'Xóa xe điện',
    group: PERMISSION_GROUP.VEHICLE,
  },
  {
    action: ACTION_CONST.LIST,
    resource: PERMISSION_RESOURCE.BOAT,
    name: 'Xem danh sách tàu thuyền',
    group: PERMISSION_GROUP.VEHICLE,
  },
  {
    action: ACTION_CONST.DETAIL,
    resource: PERMISSION_RESOURCE.BOAT,
    name: 'Xem chi tiết tàu thuyền',
    group: PERMISSION_GROUP.VEHICLE,
  },
  {
    action: ACTION_CONST.CREATE,
    resource: PERMISSION_RESOURCE.BOAT,
    name: 'Thêm mới tàu thuyền',
    group: PERMISSION_GROUP.VEHICLE,
  },
  {
    action: ACTION_CONST.UPDATE,
    resource: PERMISSION_RESOURCE.BOAT,
    name: 'Chỉnh sửa tàu thuyền',
    group: PERMISSION_GROUP.VEHICLE,
  },
  {
    action: ACTION_CONST.DELETE,
    resource: PERMISSION_RESOURCE.BOAT,
    name: 'Xóa tàu thuyền',
    group: PERMISSION_GROUP.VEHICLE,
  },
  {
    action: ACTION_CONST.LIST,
    resource: PERMISSION_RESOURCE.TRAM_POINT,
    name: 'Xem danh sách các điểm xe điện',
    group: PERMISSION_GROUP.TRAM_POINT,
  },
  {
    action: ACTION_CONST.DETAIL,
    resource: PERMISSION_RESOURCE.TRAM_POINT,
    name: 'Xem chi tiết điểm xe điện',
    group: PERMISSION_GROUP.TRAM_POINT,
  },
  {
    action: ACTION_CONST.CREATE,
    resource: PERMISSION_RESOURCE.TRAM_POINT,
    name: 'Thêm mới điểm xe điện',
    group: PERMISSION_GROUP.TRAM_POINT,
  },
  {
    action: ACTION_CONST.UPDATE,
    resource: PERMISSION_RESOURCE.TRAM_POINT,
    name: 'Chỉnh sửa điểm xe điện',
    group: PERMISSION_GROUP.TRAM_POINT,
  },
  {
    action: ACTION_CONST.DELETE,
    resource: PERMISSION_RESOURCE.TRAM_POINT,
    name: 'Xóa điểm xe điện',
    group: PERMISSION_GROUP.TRAM_POINT,
  },
  {
    action: ACTION_CONST.LIST,
    resource: PERMISSION_RESOURCE.TRIP,
    name: 'Xem danh sách hành trình',
    group: PERMISSION_GROUP.TRIP,
  },
  {
    action: ACTION_CONST.DETAIL,
    resource: PERMISSION_RESOURCE.TRIP,
    name: 'Xem chi tiết hành trình',
    group: PERMISSION_GROUP.TRIP,
  },
  {
    action: ACTION_CONST.CREATE,
    resource: PERMISSION_RESOURCE.TRIP,
    name: 'Thêm mới hành trình',
    group: PERMISSION_GROUP.TRIP,
  },
  {
    action: ACTION_CONST.UPDATE,
    resource: PERMISSION_RESOURCE.TRIP,
    name: 'Chỉnh sửa hành trình',
    group: PERMISSION_GROUP.TRIP,
  },
  {
    action: ACTION_CONST.DELETE,
    resource: PERMISSION_RESOURCE.TRIP,
    name: 'Xóa hành trình',
    group: PERMISSION_GROUP.TRIP,
  },
  {
    action: ACTION_CONST.CREATE,
    resource: PERMISSION_RESOURCE.SCHEDULE_RIDE,
    name: 'Tạo lịch',
    group: PERMISSION_GROUP.TRIP,
  },
  {
    action: ACTION_CONST.UPDATE,
    resource: PERMISSION_RESOURCE.SCHEDULE_RIDE,
    name: 'Cập nhật lịch',
    group: PERMISSION_GROUP.TRIP,
  },
  {
    action: ACTION_CONST.CREATE,
    resource: PERMISSION_RESOURCE.SCHEDULE_RIDE,
    name: 'Thiết lập thông số lập lịch tự động',
    group: PERMISSION_GROUP.TRIP,
  },
  {
    action: ACTION_CONST.LIST,
    resource: PERMISSION_RESOURCE.DRIVER,
    name: 'Xem danh sách tài xế',
    group: PERMISSION_GROUP.DRIVER,
  },
  {
    action: ACTION_CONST.DETAIL,
    resource: PERMISSION_RESOURCE.DRIVER,
    name: 'Xem chi tiết tài xế',
    group: PERMISSION_GROUP.DRIVER,
  },
  {
    action: ACTION_CONST.CREATE,
    resource: PERMISSION_RESOURCE.DRIVER,
    name: 'Thêm mới tài xế',
    group: PERMISSION_GROUP.DRIVER,
  },
  {
    action: ACTION_CONST.UPDATE,
    resource: PERMISSION_RESOURCE.DRIVER,
    name: 'Chỉnh sửa tài xế',
    group: PERMISSION_GROUP.DRIVER,
  },
  {
    action: ACTION_CONST.DISABLE,
    resource: PERMISSION_RESOURCE.DRIVER,
    name: 'Vô hiệu hóa tài khoản tài xế',
    group: PERMISSION_GROUP.DRIVER,
  },
  {
    action: ACTION_CONST.LIST,
    resource: PERMISSION_RESOURCE.POWER,
    name: 'Xem danh sách năng lượng phương tiện',
    group: PERMISSION_GROUP.POWER,
  },
  {
    action: ACTION_CONST.DETAIL,
    resource: PERMISSION_RESOURCE.POWER,
    name: 'Xem chi tiết năng lượng phương tiện',
    group: PERMISSION_GROUP.POWER,
  },
  {
    action: ACTION_CONST.UPDATE,
    resource: PERMISSION_RESOURCE.POWER,
    name: 'Điều phối nạp/xả năng lượng',
    group: PERMISSION_GROUP.POWER,
  },

  {
    action: ACTION_CONST.LIST,
    resource: PERMISSION_RESOURCE.MAP,
    name: 'Xem bản đồ xe điện',
    group: PERMISSION_GROUP.OPERATION,
  },
  {
    action: ACTION_CONST.LIST,
    resource: PERMISSION_RESOURCE.MAP,
    name: 'Xem bản đồ tàu thuyền',
    group: PERMISSION_GROUP.OPERATION,
  },
  {
    action: ACTION_CONST.LIST,
    resource: PERMISSION_RESOURCE.TRACK,
    name: 'Xem danh sách thông tin điều phối xe',
    group: PERMISSION_GROUP.OPERATION,
  },
  {
    action: ACTION_CONST.UPDATE,
    resource: PERMISSION_RESOURCE.TRACK,
    name: 'Điều xe thủ công',
    group: PERMISSION_GROUP.OPERATION,
  },
  {
    action: ACTION_CONST.UPDATE,
    resource: PERMISSION_RESOURCE.TRACK,
    name: 'Điều xe theo yêu cầu',
    group: PERMISSION_GROUP.OPERATION,
  },
  {
    action: ACTION_CONST.LIST,
    resource: PERMISSION_RESOURCE.MAINTENANCE,
    name: 'Xem danh sách bảo trì bảo dưỡng',
    group: PERMISSION_GROUP.MAINTENANCE,
  },
  {
    action: ACTION_CONST.DETAIL,
    resource: PERMISSION_RESOURCE.MAINTENANCE,
    name: 'Xem chi tiết thông tin bảo trì bảo dưỡng',
    group: PERMISSION_GROUP.MAINTENANCE,
  },
  {
    action: ACTION_CONST.CREATE,
    resource: PERMISSION_RESOURCE.MAINTENANCE,
    name: 'Thêm mới thông tin bảo trì bảo dưỡng',
    group: PERMISSION_GROUP.MAINTENANCE,
  },
  {
    action: ACTION_CONST.UPDATE,
    resource: PERMISSION_RESOURCE.MAINTENANCE,
    name: 'Chỉnh sửa thông tin bảo trì bảo dưỡng',
    group: PERMISSION_GROUP.MAINTENANCE,
  },
  {
    action: ACTION_CONST.DELETE,
    resource: PERMISSION_RESOURCE.MAINTENANCE,
    name: 'Xóa thông tin bảo trì bảo dưỡng',
    group: PERMISSION_GROUP.MAINTENANCE,
  },
  {
    action: ACTION_CONST.LIST,
    resource: PERMISSION_RESOURCE.INCIDENT,
    name: 'Xem danh sách sự cố',
    group: PERMISSION_GROUP.INCIDENT,
  },
  {
    action: ACTION_CONST.DETAIL,
    resource: PERMISSION_RESOURCE.INCIDENT,
    name: 'Xem chi tiết sự cố',
    group: PERMISSION_GROUP.INCIDENT,
  },
  {
    action: ACTION_CONST.UPDATE,
    resource: PERMISSION_RESOURCE.INCIDENT,
    name: 'Phân loại sự cố',
    group: PERMISSION_GROUP.INCIDENT,
  },
  {
    action: ACTION_CONST.UPDATE,
    resource: PERMISSION_RESOURCE.INCIDENT,
    name: 'Gửi sự cố đến bộ phận bảo dưỡng',
    group: PERMISSION_GROUP.INCIDENT,
  },
  {
    action: ACTION_CONST.LIST,
    resource: PERMISSION_RESOURCE.REPORT,
    name: 'Xem danh sách báo cáo',
    group: PERMISSION_GROUP.REPORT,
  },
  {
    action: ACTION_CONST.DETAIL,
    resource: PERMISSION_RESOURCE.REPORT,
    name: 'Xem chi tiết báo cáo',
    group: PERMISSION_GROUP.REPORT,
  },
];
